### ISSUE TITLE
.sync() command fails with Node 8

### ISSUE THREAD

**Issue by dpikt** [JeffHing/command-queue#1]
Throws `TypeError: "cwd" must be a string`

Versions:
node: `8.6.0`
command-queue: `0.1.4`

**Comment by JeffHing** [comment]
Thanks for reporting this. I'll take a look this weekend.

**Comment by JeffHing** [comment]
Whoops. Didn't mean to close this yet.

**Comment by JeffHing** [comment]
Fixed in command-queue@0.1.5.
